name: Discord Forum Bot

on:
  schedule:
    # 매일 오전 7시에 실행 (한국 시간, UTC+9) 
    # UTC 기준으로는 22시 (22:00) => 대략 40분 ~ 1시간 정도 Delay되는것 같아서 오전 7시로 수정
    - cron: "0 22 * * *"

  workflow_dispatch: # 수동 실행 가능하게 추가

jobs:
  post_message:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 필요 라이브러리 설치
        run: pip install requests

      - name: Discord 메시지 전송
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py
